### PR TITLE
Update ISChat.lua - Italian

### PR DESCRIPTION
**Pull request by ronfino**
Hi, is my fork fine? I only did some minor changes leaving the commands the way they are to not mess them up. Also, if it's okay, can it be released as an "Italian Version" or linked in the base repository?

I'm pretty new the github, don't be surprised if you notice some issues!

### CODE REVIEW

**Comment by buffyuwu** [comment]
Sure! Go ahead and pull from upstream/master to get my latest update. I'll create a separate Italian version of the mod and add you as a collaborator on Steam. Link me your steam profile :D

**Comment by ronfino** [comment]
Oof, that's sounds a bit complicated. I'm not really in to coding, "true/false" and "0/1" is the only coding knowledge i've got. Am i supposed to just click "Fetch and merge" in order to do what you just said?

https://steamcommunity.com/id/ronfino

**Comment by buffyuwu** [comment]
This is on my to-do list but I'll add you on steam once I'm ready to set the mod up.  Holidays and stuff!

**Comment by ronfino** [comment]
Thank you!

**EDIT:** I don't know how to fix the conflict since i don't have any programming knowledge as i said, but you can still use what i translated in my fork as a reference and easily make a commit.

**Comment by buffyuwu** [comment]
> Thank you!
> 
> **EDIT:** I don't know how to fix the conflict since i don't have any programming knowledge as i said, but you can still use what i translated in my fork as a reference and easily make a commit.

That's okay!! What I recommend you do is to make your fork the Italian repository, and upload the mod as the Italian version separate. All you'll need to do is attribute this repository as what the code is based on both on your repo and on the workshop page. Make sure to include things like the license on the workshop page especially to avoid anyone reporting your mod for theft!!!

image
Like I've done here, with a link to my repository's licensing page. You'd link to your fork's licensing page.

**Comment by buffyuwu** [comment]
:)

**Comment by buffyuwu** [comment]
if you have any questions feel free to reach out to me on discord via www.necropolisrp.net

**Comment by ronfino** [comment]
I didn't expect it to be this difficult, i think i will not work on it anymore. I appreciate your availability though, hopefully someone else will make an italian version. Bye!

**Pull request closed without merging**
